version: "2.6"
services:
  apachejenkins:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: apachejenkins-service
    restart: always
#    ports:
#      - 8020:8020
    labels:
      - "traefik.http.routers.apachejenkins.rule=Host(`pregps.dmetrix.cl`) && PathPrefix(`/jenkins/test`)"
      - "traefik.port=80"
      - "traefik.http.services.apachejenkins.loadbalancer.server.port=80"
      - "traefik.http.routers.apachejenkins.entrypoints=websecurity"
      - "traefik.http.routers.apachejenkins.tls.certresolver=myresolver"
    networks:
      - traefik_network
#    volumes:
#      - schemas:/usr/share/commons:rw
networks:
  traefik_network:
    name: traefik_net
    driver: bridge